### ISSUE TITLE
[bug]websocket connection failed because WSAStartup not called on windows

### ISSUE THREAD

**Issue by hongyue** [machinezone/IXWebSocket#100]
problem: websocket connection failed because WSAStartup not called on windows
version 4.0.3
source: vcpkg

I need to call the WSAStartup and WSACleanup functions manually, and docs doesn't say it...
when I built it from the latest source code, the poll.h header is missing, does it support windows in the future?

**Comment by bsergean** [comment]
Thanks, I've updated the README in f9178f5 to talk about that Windows init phase.

**Comment by bsergean** [comment]
With respect to poll, that doc says that WinSock2.h is sufficient. If not, could you try to change IXNetSystem.h and add the right header so that things compile fine, and then send me a diff or make a pull request.

I *really want* to support Windows, and I'm very interested in feedback on this platform. I don't have an easy access to a windows machine which is why the experience is a bit rocky on Windows, compared to the other platforms.

**Comment by hongyue** [comment]
I think to encapsulate the calling of WSAStartup and WSACleanup function in the library maybe better.
I'm not familiar with Win32 programming, so I can't help to fix the header problem.

PS: the readme now looks like a little messy.

**Comment by bsergean** [comment]
I prefer having users read the doc (fixed now, indeed the README was messed up) and call those init function manually, than having to call it for them and litter the code with static calls, that init code belongs in main.

Ok the init problem is fixed I'll make another issue for the poll.h build error.

**Comment by bsergean** [comment]
@hongyue, could you paste the build error in #101 please ?
