### ISSUE TITLE
Fin fragment between IXWebSocket and WebSocket-Node

### ISSUE THREAD

**Issue by aelimport** [machinezone/IXWebSocket#131]
Hello, 
first of all- thanks for the great library. I tried a couple of different libraries and this was one that worked best for me (especially because of no dependencies to boost/asio or smth).

But I have an issue. I have two applications that are connected through websockets to each other. The server is connected to some hardware (the drivers and api for this hardware are only in C/C++) and the UI is in JavaScript and HTML and is sending commands to the server. I could establish the connection and I can send simple commands or packages (JSON) from each side. But if I am trying to send some large Project (something about 150MB) it never arrive by the client (Node.JS). 
I played a littlebit with ix::OnProgressCallback and just printed the current fragments/total to see if all packages comes through. It seems like they are all sent, but they still don't arrive or the event on the Node.JS is never triggered, except I close the Server then it seems to get the last fragment and the event is triggered. Then I added some sleep by the callback: 

```
if (client->getReadyState() == ix::ReadyState::Open) {
  client->send(package, false, [](int current, int total) -> bool{
	wxThread::Sleep(10);
	return true;
  });
}
```

and voilà it works now. But I don't like this workaround, because I have to send a lot of data through the socket and I would like to do without a pause.

This is how I initilize the client on Node.JS side

`this.client = new WebSocket({
      closeTimeout: 20000,
      maxReceivedFrameSize: 1 << 20,
      maxReceivedMessageSize: 500 * 1024 * 1024,
      fragmentationThreshold: 1 << 15
    });`

Does anyone have an idea how to abstain the pause? Thank you.

**Comment by aelimport** [comment]
Now I tried the remote connection over internet. It seems, with higher latency it needs a bigger pause.

**Comment by bsergean** [comment]
Hey @aelimport thanks for the good words about the library.

Are you on Windows ? There is a unittest which test sending large messages (capped to 1M right now so that the test does not take forever), but that test is disabled on Windows... I remember running into that same problem, but fixing, and maybe it regressed since. The problem I believe is that the kernel send queue gets full, and the TCP flow control kicks in. send should fail.

```
     [ENOBUFS]          The output queue for a network interface is full.
                        This generally indicates that the interface has
                        stopped sending, but may be caused by transient
                        congestion.
```

The way the code handles this is that when this happens, the sender notify the background thread to try to flush the send buffer, and there's code which calls isReadyToWrite (which polls the socket for 'writability'), and then try to continue and flush the send queue. But it could be buggy, or not work well on Windows. As a matter of fact that unittest is disabled on Windows.
The SelectInterrupt is not implement on Windows as I cannot use select to monitor pipes. We would have to support this properly but I'm not sure how yet.

**Comment by aelimport** [comment]
Thanks You for your reply. The problem I have is that there is no error. Sending the message does not fail. Well if there is no other solution, than I have to stay with the pause.

**Comment by bsergean** [comment]
The pause is the only workaround I can think about now.

Can you tell me what version you are using, and what operating system you are using ?

**Comment by aelimport** [comment]
It should be the latest from master branch- 7.4.4. This is what IXWebSocketVersion.h says. 
I'm on windows.

**Comment by bsergean** [comment]
Got it. Version v7.5.3 has a potential fix, could you give it a try ?

**Comment by aelimport** [comment]
Wow. It looks promising. Thank you. I'll test it little bit more when the device (microscope) is back. Now I can just load the projects. But it works now and that was the only problem.

**Comment by bsergean** [comment]
Looks like this is fixed. Please re-open otherwise.
