### ISSUE TITLE
Connection issue to SSL enabled WebSocket server

### ISSUE THREAD

**Issue by AndreasAakerberg** [machinezone/IXWebSocket#164]
Hi, thank you for creating this great library.

I do however have an issue when trying to connect to a SSL enabled WebSocket server. I'm running under Ubuntu 16.04 and have build the lib with -DUSE_TLS=1, and use untrusted-ca-key and cert files created using your generate-certs.sh script. When i attempt to connect to the server i get the following error: 

`WebSocketServer::handleConnection() HTTP status: 400 error: Invalid HTTP method, need GET, got `

If i attempt to connect to the server without TLS (i.e. use ws instead of wss) everything works fine. I have tried connecting to the sever using both a websocket client built using this lib and websocat, but the error remains. Any ideas? Thanks.

**Comment by bsergean** [comment]
Thanks for the good words and using the lib.

It could be a bug in the library, but I have a feeling it is a configuration problem.

Are you passing similar certs as arguments to your server ?

1. Configure nginx as a proxy, let it handle SSL, and talk to your server through a non encrypted connection.
2. Can you reproduce the problem with the ws command line tool (you could use ws connect just to connect to your websocket server).
3. You can try to use mbedtls instead of OpenSSL.
4. Is your server accessible to anyone, or behind a firewall ? Could I reproduce the problem ?
5. I'm no expert with SSL ...

Here is an example nginx config file for that. My websocket server runs on port 8766 here.

$ cat nginx.conf 
error_log stderr warn;

daemon off;

events {
    worker_connections 32;
}

http {

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    upstream websocket {
        server localhost:8766;
    }

    server {
        listen 8765 ssl;

        ssl_certificate     trusted-client-crt.pem;
        ssl_certificate_key trusted-client-key.pem;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://websocket;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
    }
}

**Comment by bsergean** [comment]
Another thing to try. Fetch the lib and build ws. Then jump into the ws folder, and type `env WITH_TLS=1 sh test_ws.sh`.

This will run a full test over SSL. You can peak at the script and make sure you are passing all the ssl args (key, cert, ca-chain) properly in your own example.

**Comment by AndreasAakerberg** [comment]
Thank your for your suggestions. I found the issue, it's working now after i set `tlsOptions.tls = true;` I think this should be mentioned in the docs under examples and the "TLS support and configuration" section.

**Comment by bsergean** [comment]
I updated the doc, glad that you found the problem.

Ironically a couple of days ago I was trying to setup a unit-test with tls ... and it wasn't working probably for the same reason.
