### ISSUE TITLE
Receiving fragmented Messages

### ISSUE THREAD

**Issue by rafalsk** [machinezone/IXWebSocket#236]
How does one go about receiving large Messages? When sending >500kb from Chrome, a couple of Fragment packets arrive, all with 0bytes within data-field (as reported by lib.) and no Message event is fired.

**Comment by bsergean** [comment]
The fragment messages are sent so that you can implement a progress bar or equivalent. The last message will contains the full payload.

There is an interactive test

make ws_install
cd ws
sh test_ws.sh

The unittest has a test for it too

Please provide a repro as this should work. The repro can implement ws send in javascript. (see ws source code), so that you can test it with ws transfer + ws receive.
