### ISSUE TITLE
How to correctly stop the server from message callback

### ISSUE THREAD

**Issue by EdwardClements** [machinezone/IXWebSocket#270]
Hi, I have written a command-line IXServer on Windows (using Visual Stidio 2019) and I am looking for a way for a client to tell the server to stop altogether.

Calling `server.stop()` from within the callback goes to `SocketServer::stop()`, but hangs on the `_gcThread.join();` line.

I have also tried
```
			webSocket.close();
			Sleep(100);
			webSocket.stop();
			Sleep(100);
			server.stop();
```
but with the same result.

What would be the best way of doing this?

**Comment by bsergean** [comment]
This is a rare requirement ; imagine if you could tell google.com to shutdown by sending it a special http request :).

This should be possible but I'm not sure how to do this. It will help if you close the websocket client.

**Comment by desalema70** [comment]
I have the same issue. I run the websocket as a client in my own thread (for reasons) and use "connect" and "run"; when I call "stop" from another thread the whole program hangs on joining that thread because websocket's internal loop (WebSocket::run()) never exits. I verified that the running state is "closed"; it is. By examining further I see that:

(1) The atomic "_stop" that would otherwise break the loop is not set when not running with websocket's own thread.
(2) The socket I opened is (by default) auto-reconnect, which (I presume) erases the stop status set by "stop".

I can circumvent the issue by setting "_stop" outside the joinable() test; or if I explicitly disable auto-reconnect. Either solves my issue. However I find this unsettling: if I call "stop" on the websocket, I would expect it to stop regardless of how it was set up wrt auto-reconnect or threading.

Would you like me to submit a PR? Basically I'd move "_stop = true" outside the joinable scope and also set "_stop" at an appropriate point in "WebSocket::connect".

Or, if that does not satisfy, can you tell me what the correct solution would be from a user's perspective? Thanks.

**Comment by bsergean** [comment]
Sorry I'm a bit afraid to change that logic, which took a while to solidify, and I'd prefer to keep the code as is.
