### ISSUE TITLE
VS Code Build and Compile errors

### ISSUE THREAD

**Issue by sparks2021** [machinezone/IXWebSocket#295]
Hello,

I am new to C++, and am working on a secured websocket (wss) implementation project. My setup is Ubuntu OS 20.04, and have installed regular packages. I use VS COde IDE for c++ dev. I am trying to get going on a basic project using IXWS and am running into issues, and am hoping team here will help me out. Here is the flow:

$> mkdir evsclient
$> cd evsclient
$> evsclient: git clone https://github.com/machinezone/IXWebSocket.git
$> evsclient: cd IXWebSocket
$> evsclient/IXWebSocket: mkdir build
$> evsclient/IXWebSocket: cd build
$> evsclient/IXWebSocket/build: cmake -DUSE_TLS=1 ..
$> evsclient/IXWebSocket/build: make -j
$> evsclient/IXWebSocket/build: sudo make install

i do not get any issues. then i go one folder up.

$> evsclient/IXWebSocket/build: cd ..
$> evsclient/IXWebSocket: code .

At this point VS Code launches.

I open main.cpp

Now in VSC, I click on RUN ->Start without Debugging -> C/C++ GDB. I pick g++ build and debug active file. Then it tries to create both launch.json and tasks.json.

However, i get build errors, and IDE exits with code 1. What am i doing wrong. how to fix this ?

TERMINAL OUTPUT:
> Executing task: C/C++: g++ build active file <

Starting build...
/usr/bin/g++ -g /home/sagar/evsclient/IXWebSocket/main.cpp -o /home/sagar/evsclient/IXWebSocket/main
/usr/bin/ld: /tmp/cc3mxFaA.o: in function `main':
/home/sagar/evsclient/IXWebSocket/main.cpp:27: undefined reference to `ix::WebSocket::WebSocket()'
/usr/bin/ld: /home/sagar/evsclient/IXWebSocket/main.cpp:32: undefined reference to `ix::WebSocket::setUrl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /home/sagar/evsclient/IXWebSocket/main.cpp:34: undefined reference to `ix::userAgent[abi:cxx11]()'
/usr/bin/ld: /home/sagar/evsclient/IXWebSocket/main.cpp:39: undefined reference to `ix::WebSocket::setOnMessageCallback(std::function<void (std::unique_ptr<ix::WebSocketMessage, std::default_delete<ix::WebSocketMessage> > const&)> const&)'
/usr/bin/ld: /home/sagar/evsclient/IXWebSocket/main.cpp:61: undefined reference to `ix::WebSocket::start()'
/usr/bin/ld: /home/sagar/evsclient/IXWebSocket/main.cpp:64: undefined reference to `ix::WebSocket::send(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::function<bool (int, int)> const&)'
/usr/bin/ld: /home/sagar/evsclient/IXWebSocket/main.cpp:74: undefined reference to `ix::WebSocket::send(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::function<bool (int, int)> const&)'
/usr/bin/ld: /home/sagar/evsclient/IXWebSocket/main.cpp:27: undefined reference to `ix::WebSocket::~WebSocket()'
/usr/bin/ld: /home/sagar/evsclient/IXWebSocket/main.cpp:27: undefined reference to `ix::WebSocket::~WebSocket()'
collect2: error: ld returned 1 exit status

here is my launch.json file
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: g++ build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}

hERE IS MY TASKS.JSON
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++ build active file",
            "command": "/usr/bin/g++",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}

**Comment by bsergean** [comment]
I think your problem is that you are not linking with the library.

-lixwebsocket might do it.

Try this https://stackoverflow.com/questions/52910102/vscode-c-task-json-include-path-and-libraries ?

**Comment by sparks2021** [comment]
Thanks bsergean for promt response. I tried many things in the last few hours, and seem to be gettting this wrong. Is there a simple guide or step/by/step sequence you guys can put togeather for rookies like me to get past the setup issues.

I tried many combinations or c_cpp_properties.json in vscode, launch.json and tasks.json - without success.

then i ditched vs code completely, and went back to terminal. so after building (i.e., after sudo make install). i came up from the build folder. And tried compiling + linking with : g++ -o main main.cpp -lixwebsocket and many other commands...even tried clang++....but was not able to get past this....

i suspect its something very simple...is there a small usage or setup tutorial you guys can put togeather please...it will be very helpful..

**Comment by bsergean** [comment]
sorry I cannot help better / you could try to use vcpkg, ixwebsocket is packaged there.

I also suspect it is something simple

**Comment by SlokaTech-Git** [comment]
Hi Sergean, I am Kiran P working on sparks2021. I am still facing issues after using vcpkg. I am giving below each and every step what i followed and copied the errors which I faced in each step. Can you please look into it and guide us?

1.	Downloaded the ixwebsockets from github (https://github.com/machinezone/IXWebSocket.git)
2.	Ran below commands:
a.	mkdir build # make a build dir so that you can build out of tree.
b.	cd build
c.	cmake -DUSE_TLS=1 ..
d.	make -j
e.	make install # it install to /usr/local on Unix
f.	sudo chown -R `whoami`:administrator /usr/local
3.	ran the below command. I tried with –std=c++11, –std=c++14, –std=c++17, –std=c++s0,
clang++ --std=c++17 --stdlib=libc++ -lc++abi main.cpp -lstdc++fs -lixwebsocket -lz -framework Security -framework Foundation
a.	Got Below Error:
main.cpp:4:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.
4.	gcc version
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 10.2.0-5ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-WJNXnb/gcc-10-10.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-WJNXnb/gcc-10-10.2.0/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (Ubuntu 10.2.0-5ubuntu1~20.04)
5.	clang version
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
6.	The project Folder contains below files:
a.	Ixwebsocket -It contains ixwebsockets cpp and header files
b.	Main.cpp
#include <iostream>
#include <ixwebsocket/IXWebSocket.h>
#include <ixwebsocket/IXNetSystem.h>
int main(){
    ix::WebSocket webSocket;
    std::string url("ws://localhost:8080/");
webSocket.setUrl(url);
// Optional heart beat, sent every 45 seconds when there is not any traffic
// to make sure that load balancers do not kill an idle connection.
webSocket.setPingInterval(45);
// Per message deflate connection is enabled by default. You can tweak its parameters or disable it
webSocket.disablePerMessageDeflate();
// Setup a callback to be fired when a message or an event (open, close, error) is received
webSocket.setOnMessageCallback([](const ix::WebSocketMessagePtr& msg)
    {
        if (msg->type == ix::WebSocketMessageType::Message)
        {
            std::cout << msg->str << std::endl;
        }    });
// Now that our callback is setup, we can start our background thread and receive messages
webSocket.start();
// Send a message to the server (default to TEXT mode)
webSocket.send("hello world");
// The message can be sent in BINARY mode (useful if you send MsgPack data for example)
webSocket.sendBinary("some serialized binary data");
// ... finally ...
// Stop the connection
webSocket.stop();
    printf("Hello Babu... Nidra le..");
}
7.	After suggestion of using vcpkg. Installed vcpkg from git hub (https://github.com/microsoft/vcpkg)
a.	$ git clone https://github.com/microsoft/vcpkg
b.	$ ./vcpkg/bootstrap-vcpkg.sh
c.	./vcpkg/vcpkg install ixwebsockets  #it installed all ixwebsocket package and its dependencies

8.	Created CMakeLists.txt file in the project
cmake_minimum_required(VERSION 3.16.3)
project(EVSCPP)
#set(CMAKE_TOOLCHAIN_FILE "/vcpkg/scripts/buildsystems/vcpkg.cmake" CACHE STRING "vcpkg installation file)
# find library and its headers
find_path(IXWEBSOCKET_INCLUDE_DIR ixwebsocket/IXWebSocket.h)
find_library(IXWEBSOCKET_LIBRARY ixwebsocket)
# include headers
include_directories(${IXWEBSOCKET_INCLUDE_DIR})
add_executable(${PROJECT_NAME} main.cpp)
# ...
target_link_libraries(${PROJECT_NAME} ${IXWEBSOCKET_LIBRARY})
9.	Then ran the below commands:
a.	sudo cmake -B build/ -S . -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/administrator/Desktop/evSparksWS/evSparksCPP/build
b.	sudo cmake --build build/

10.	After running the 10.b command, I am getting below errors
[ 50%] Linking CXX executable EVSCPP
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXWebSocket.cpp.o): in function `ix::WebSocket::start()':
IXWebSocket.cpp:(.text+0x240d): undefined reference to `pthread_create'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXWebSocket.cpp.o): in function `ix::WebSocket::checkConnection(bool)':
IXWebSocket.cpp:(.text+0x616d): undefined reference to `pthread_cond_clockwait'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXWebSocketPerMessageDeflateCodec.cpp.o): in function `bool ix::WebSocketPerMessageDeflateCompressor::compressData<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) [clone .part.0]':
IXWebSocketPerMessageDeflateCodec.cpp:(.text+0x77): undefined reference to `deflate'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXWebSocketPerMessageDeflateCodec.cpp.o): in function `ix::WebSocketPerMessageDeflateCompressor::~WebSocketPerMessageDeflateCompressor()':
IXWebSocketPerMessageDeflateCodec.cpp:(.text+0x390): undefined reference to `deflateEnd'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXWebSocketPerMessageDeflateCodec.cpp.o): in function `ix::WebSocketPerMessageDeflateCompressor::init(unsigned char, bool)':
IXWebSocketPerMessageDeflateCodec.cpp:(.text+0x3da): undefined reference to `deflateInit2_'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXWebSocketPerMessageDeflateCodec.cpp.o): in function `ix::WebSocketPerMessageDeflateDecompressor::~WebSocketPerMessageDeflateDecompressor()':
IXWebSocketPerMessageDeflateCodec.cpp:(.text+0x6a0): undefined reference to `inflateEnd'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXWebSocketPerMessageDeflateCodec.cpp.o): in function `ix::WebSocketPerMessageDeflateDecompressor::init(unsigned char, bool)':
IXWebSocketPerMessageDeflateCodec.cpp:(.text+0x6d9): undefined reference to `inflateInit2_'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXWebSocketPerMessageDeflateCodec.cpp.o): in function `ix::WebSocketPerMessageDeflateDecompressor::decompress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
IXWebSocketPerMessageDeflateCodec.cpp:(.text+0x846): undefined reference to `inflate'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXWebSocketPerMessageDeflateCodec.cpp.o): in function `bool ix::WebSocketPerMessageDeflateCompressor::compressData<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<unsigned char, std::allocator<unsigned char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<unsigned char, std::allocator<unsigned char> >&) [clone .part.0]':
IXWebSocketPerMessageDeflateCodec.cpp:(.text+0x98d): undefined reference to `deflate'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): in function `ix::SocketOpenSSL::openSSLInitialize()':
IXSocketOpenSSL.cpp:(.text+0x20): undefined reference to `OPENSSL_init_ssl'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2d): undefined reference to `OPENSSL_init_ssl'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x39): undefined reference to `OPENSSL_init_ssl'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): in function `ix::SocketOpenSSL::send(char*, unsigned long)':
IXSocketOpenSSL.cpp:(.text+0x93): undefined reference to `ERR_clear_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xa2): undefined reference to `SSL_write'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xb1): undefined reference to `SSL_get_error'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): in function `ix::SocketOpenSSL::recv(void*, unsigned long)':
IXSocketOpenSSL.cpp:(.text+0x157): undefined reference to `ERR_clear_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x166): undefined reference to `SSL_read'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x197): undefined reference to `SSL_get_error'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): in function `ix::SocketOpenSSL::getSSLError[abi:cxx11](int)':
IXSocketOpenSSL.cpp:(.text+0x82a): undefined reference to `SSL_get_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x961): undefined reference to `ERR_get_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xb11): undefined reference to `ERR_get_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xb76): undefined reference to `ERR_error_string'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xcae): undefined reference to `ERR_error_string'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): in function `ix::SocketOpenSSL::openSSLCreateContext(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
IXSocketOpenSSL.cpp:(.text+0xd6f): undefined reference to `TLS_client_method'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xd83): undefined reference to `SSL_CTX_new'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xd9f): undefined reference to `SSL_CTX_ctrl'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xdac): undefined reference to `SSL_CTX_set_options'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): in function `ix::SocketOpenSSL::openSSLAddCARootsFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
IXSocketOpenSSL.cpp:(.text+0xdf4): undefined reference to `SSL_CTX_get_cert_store'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xe0d): undefined reference to `X509_STORE_set_flags'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xe18): undefined reference to `BIO_new_mem_buf'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xe31): undefined reference to `ERR_clear_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xe3c): undefined reference to `X509_STORE_add_cert'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xe45): undefined reference to `ERR_get_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xe65): undefined reference to `X509_free'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xe74): undefined reference to `PEM_read_bio_X509_AUX'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xe81): undefined reference to `ERR_clear_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xe8f): undefined reference to `BIO_free'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xeb7): undefined reference to `X509_free'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): in function `ix::SocketOpenSSL::openSSLCheckServerCert(ssl_st*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
IXSocketOpenSSL.cpp:(.text+0xeec): undefined reference to `SSL_get_peer_certificate'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xef9): undefined reference to `X509_free'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): in function `ix::SocketOpenSSL::openSSLClientHandshake(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool ()> const&)':
IXSocketOpenSSL.cpp:(.text+0xf7d): undefined reference to `ERR_clear_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xf86): undefined reference to `SSL_connect'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0xf99): undefined reference to `SSL_get_error'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): in function `ix::SocketOpenSSL::openSSLServerHandshake(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
IXSocketOpenSSL.cpp:(.text+0x1150): undefined reference to `ERR_clear_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x1159): undefined reference to `SSL_accept'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x116c): undefined reference to `SSL_get_error'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): in function `ix::SocketOpenSSL::handleTLSOptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
IXSocketOpenSSL.cpp:(.text+0x12d3): undefined reference to `ERR_clear_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x12f0): undefined reference to `SSL_CTX_use_certificate_chain_file'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x12fe): undefined reference to `ERR_get_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x1486): undefined reference to `ERR_error_string'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x14bb): undefined reference to `ERR_clear_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x14d7): undefined reference to `SSL_CTX_set_verify'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x14fa): undefined reference to `SSL_CTX_set_cipher_list'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x1555): undefined reference to `SSL_CTX_set_default_verify_paths'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x1572): undefined reference to `SSL_CTX_set_verify'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x1580): undefined reference to `SSL_CTX_set_verify_depth'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x15a3): undefined reference to `SSL_CTX_set_cipher_list'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x15b1): undefined reference to `ERR_get_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x1742): undefined reference to `ERR_error_string'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x1836): undefined reference to `SSL_CTX_use_PrivateKey_file'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x1844): undefined reference to `ERR_get_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x19b6): undefined reference to `SSL_CTX_load_verify_locations'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x19c4): undefined reference to `ERR_get_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x1b61): undefined reference to `ERR_get_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x1b91): undefined reference to `ERR_get_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x1d22): undefined reference to `ERR_error_string'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x1dbd): undefined reference to `SSL_CTX_check_private_key'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x1dca): undefined reference to `ERR_get_error'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): in function `ix::SocketOpenSSL::close()':
IXSocketOpenSSL.cpp:(.text+0x2504): undefined reference to `SSL_free'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x251a): undefined reference to `SSL_CTX_free'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): in function `ix::SocketOpenSSL::accept(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
IXSocketOpenSSL.cpp:(.text+0x268d): undefined reference to `TLS_server_method'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x26a2): undefined reference to `SSL_CTX_new'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x26c3): undefined reference to `SSL_CTX_ctrl'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x26d8): undefined reference to `SSL_CTX_ctrl'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x26e6): undefined reference to `SSL_CTX_set_options'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x26f6): undefined reference to `ERR_clear_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2717): undefined reference to `SSL_CTX_use_certificate_chain_file'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2725): undefined reference to `ERR_get_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2898): undefined reference to `ERR_error_string'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x28ce): undefined reference to `ERR_clear_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x28f7): undefined reference to `SSL_CTX_set_default_verify_paths'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x290f): undefined reference to `SSL_CTX_set_verify'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x291d): undefined reference to `SSL_CTX_set_verify_depth'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x293d): undefined reference to `SSL_CTX_set_cipher_list'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x294b): undefined reference to `SSL_new'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2964): undefined reference to `SSL_set_fd'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x29f8): undefined reference to `SSL_CTX_set_cipher_list'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2a11): undefined reference to `SSL_CTX_set_verify'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2a70): undefined reference to `SSL_load_client_CA_file'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2a85): undefined reference to `SSL_CTX_set_client_CA_list'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2a95): undefined reference to `SSL_CTX_load_verify_locations'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2aa3): undefined reference to `ERR_get_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2c1f): undefined reference to `ERR_error_string'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2c6e): undefined reference to `SSL_CTX_use_PrivateKey_file'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2c7c): undefined reference to `ERR_get_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2df5): undefined reference to `ERR_error_string'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2ec9): undefined reference to `ERR_get_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2ef2): undefined reference to `ERR_error_string'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x2fd1): undefined reference to `SSL_CTX_free'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x3051): undefined reference to `ERR_get_error'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x31cd): undefined reference to `ERR_error_string'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXSocketOpenSSL.cpp.o): in function `ix::SocketOpenSSL::connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool ()> const&)':
IXSocketOpenSSL.cpp:(.text+0x35c5): undefined reference to `SSL_new'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x35da): undefined reference to `SSL_set_fd'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x35ee): undefined reference to `SSL_ctrl'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x35f7): undefined reference to `SSL_get0_param'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x3605): undefined reference to `X509_VERIFY_PARAM_set1_host'
/usr/bin/ld: IXSocketOpenSSL.cpp:(.text+0x3661): undefined reference to `SSL_CTX_free'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXDNSLookup.cpp.o): in function `ix::DNSLookup::resolveCancellable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool ()> const&)':
IXDNSLookup.cpp:(.text+0xa90): undefined reference to `pthread_create'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXGzipCodec.cpp.o): in function `ix::gzipCompress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
IXGzipCodec.cpp:(.text+0x8a): undefined reference to `deflateInit2_'
/usr/bin/ld: IXGzipCodec.cpp:(.text+0xda): undefined reference to `deflate'
/usr/bin/ld: IXGzipCodec.cpp:(.text+0x110): undefined reference to `deflateEnd'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXGzipCodec.cpp.o): in function `ix::gzipDecompress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
IXGzipCodec.cpp:(.text+0x1c6): undefined reference to `inflateInit2_'
/usr/bin/ld: IXGzipCodec.cpp:(.text+0x23b): undefined reference to `inflate'
/usr/bin/ld: IXGzipCodec.cpp:(.text+0x24b): undefined reference to `inflateEnd'
/usr/bin/ld: IXGzipCodec.cpp:(.text+0x284): undefined reference to `inflateEnd'
/usr/bin/ld: /vcpkg/installed/x64-linux/lib/libixwebsocket.a(IXSetThreadName.cpp.o): in function `ix::setThreadName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
IXSetThreadName.cpp:(.text+0x6d): undefined reference to `pthread_setname_np'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/EVSCPP.dir/build.make:85: EVSCPP] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/EVSCPP.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by SlokaTech-Git** [comment]
Hi Sergean, We got the fix by below command.

clang++ -L /usr/lib/gcc/x86_64_linux-gnu/10 --std=c++17 -lstdc++ main.cpp -L /usr/local/lib -lixwebsocket -lz -pthread -lssl -crypto

**Comment by bsergean** [comment]
Looks like you figured out your build problem, closing then.
