### ISSUE TITLE
Close description can be un-initialized at time

### ISSUE THREAD

**Issue by bsergean** [machinezone/IXWebSocket#33]
We can see this easily by running continuously `make ws_test`. In that run below it it set to Normal closure / but at other times it is set to '%'.

@Dimon4eg + @Kumamon38 / This is likely a regression of 935e6791a35a48d1f4d41b767696c2101ac1f476

I think this is why I was only setting the close reason only once in a weird way, like the first time it gets sets in one of the callbacks.

```
Received 61 bytes
ws_transfer: 0 bytes left to be sent
ws_send: received message (61 bytes)
Done !
ws_send: connection closed: code 1000 reason Normal closure

Closed connection code 1000 reason %
WebSocketServer::handleConnection() done
Received file does exists, exiting loop
1897227451 20480000 /tmp/ws_test/send/20M_file
1897227451 20480000 /tmp/ws_test/receive/20M_file
Done !
Closed connection code ws_receive: connection closed: code 1000 reason Normal closure
0
 reason 
WebSocketServer::handleConnection() done
```

another run

```
ws_send: received message (61 bytes)
ws_send: connection closed: code 1000 reason Normal closure

Closed connection code 1000 reason ??
WebSocketServer::handleConnection() done
Received file does exists, exiting loop
4293923412 20480000 /tmp/ws_test/send/20M_file
4293923412 20480000 /tmp/ws_test/receive/20M_file
Done !
ws_receive: connection closed: code 1000 reason Normal closure
Closed connection
 code 1000 reason ac
```

**Comment by bsergean** [comment]
I'll take a look when I have time but if you have an idea for a fix please go ahead :)

**Comment by bsergean** [comment]
ps: I should say that I am not positive that it is a regression, but it is still a bug.

**Comment by Kumamon38** [comment]
I had a look and created a PR to fix this, but in fact this was nothing to do with the #28 
- First, when we receive the close code / reason remotely, the reason had 2 characters more than it needed (that why we could see "ac" or "%" or whatever randomnly read from memory)
- Second, when we used the close() method, we sent the code but not the reason, so we can't expect to read it on the other side
- Not directly linked, but we can call the `_onCloseCallback(_closeCode, _closeReason, _closeWireSize);` with not really initialized value (0, "", 0) in the case we call `setReadyState(CLOSED)` outside the `close()` method

All of this should be fixed in PR #34

**Comment by Kumamon38** [comment]
So is the issue fixed as you wanted with last PR?

**Comment by bsergean** [comment]
`make ws_test` seems to behave now !

**Comment by bsergean** [comment]
I think that the next step here is to add the ability to specify a reason and a code when calling websocket.close, but that might be very easy.

**Comment by Kumamon38** [comment]
Just 2 parameters to add; you can if you want to :)

**Comment by bsergean** [comment]
Doing it now ... :)
