### ISSUE TITLE
Is it possible to cancel an HTTP Request?

### ISSUE THREAD

**Issue by natano** [machinezone/IXWebSocket#331]
I currently use `performRequest()` to perform a an asynchronous HTTP request. Is it possible to cancel the request when I'm not interested in the result anymore for some reason (think arbitrary cancel, not timeout)? Looking at the code [this](https://github.com/machinezone/IXWebSocket/blob/master/ixwebsocket/IXHttpClient.cpp#L244-L289) would look like the right place to add support for that.

**Comment by natano** [comment]
I looked a bit more at the code and came up with PR #332 . It seems to work, but I'm not really familiar with the codebase.

**Comment by bsergean** [comment]
I added comments in the pull requests, the code change looks good but it would be good to have a unittest too. For example the unittest would use a simple server that hangs, say for a few seconds, and the cancellation happens before that. We might need a special error code to be returned probably for when the cancellation happens, so that the test can check against it. There might be an existing code for that, or a new one which would be UserCancellationRequested or what not.

**Comment by natano** [comment]
Thank you for the comments! I'll update the PR in the next couple of days.

**Comment by bsergean** [comment]
Thanks for the contribution and effort to add a test.
